#!/usr/bin/env bash
set -e

git clone https://github.com/alejoe91/spikeinterface.git
cd spikeinterface
git checkout 845fd25f8d46434f52eccc3e3db154d4d277cfc9
pip install .
cd ..

git clone https://github.com/SpikeInterface/probeinterface.git
cd probeinterface
git checkout 0c10fd3c165289a999da764e47cd27617f29961f
pip install .
cd ..