#!/usr/bin/env bash
set -e

git clone https://github.com/alejoe91/spikeinterface.git
cd spikeinterface
git checkout ebe38440bc646aaffe980294de5d63caa385e99a
pip install .
cd ..

git clone https://github.com/SpikeInterface/probeinterface.git
cd probeinterface
git checkout 0c10fd3c165289a999da764e47cd27617f29961f
pip install .
cd ..